name: Build and update docs
# Publish docs when new commit containing doc changes only
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
        - 'README.md'
        - 'docs/**'
        - 'mkdocs.yml'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Requirements
        run: make install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build and publish docs
        run: make publish-docs

